- name: Install some packages
  apt:
    name:
      - selinux-utils
      - semanage-utils
      - semodule-utils
      - checkpolicy
      - semanage-utils
      - semodule-utils
      - python3-sepolgen
      - policycoreutils
      - setools
      - sepol-utils
    state: present

- name: Download some packages
  get_url:
    url: "{{item}}"
    dest: /tmp/
  with_items:
    - http://ftp.de.debian.org/debian/pool/main/s/selinux-basics/selinux-basics_0.5.6_all.deb
    - http://ftp.de.debian.org/debian/pool/main/r/refpolicy/selinux-policy-default_2.20190201-2_all.deb
    - http://ftp.de.debian.org/debian/pool/main/s/selinux-python/policycoreutils-python-utils_2.8-3_all.deb
    - http://ftp.de.debian.org/debian/pool/main/r/refpolicy/selinux-policy-src_2.20190201-2_all.deb
    - http://ftp.de.debian.org/debian/pool/main/s/selinux-python/policycoreutils-dev_2.8-3_amd64.deb
    - http://ftp.de.debian.org/debian/pool/main/r/refpolicy/selinux-policy-dev_2.20190201-2_all.deb

- name: Install some packages via apt
  shell: apt -y install /tmp/selinux-* /tmp/policy*

- name: Install some packages via dpkg
  shell: dpkg -i /tmp/selinux-* /tmp/policy*

- name: Activate selinux
  command: selinux-activate

- name: Set default kernel grub
  block:
    - name: Set default kernel grub Line
      lineinfile:
        path: /etc/default/grub
        regexp: ^GRUB_CMDLINE_LINUX=
        line: GRUB_CMDLINE_LINUX=" security=selinux enforce=0"
        state: present
      register: result
    - name: Set default kernel grub Update grub
      command: update-grub
      when: result.changed
    - name: Set default kernel grub Reboot
      reboot:
        reboot_timeout: 60
      when: result.changed
